spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
  thymeleaf:
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    template-resolver-order: 1
  http:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

  mail:
      default-encoding: UTF-8
      host: smtp.gmail.com
      username: Doctor.Patratiy.Office@gmail.com
      password: doctor-office
      port: 587
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
      protocol: smtp
      test-connection: false

tokenExpiration:
      resetPassword: 60
      verificationTime: 3600